// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cmd

import (
	"context"
	"fmt"

	"github.com/openai/openai-cli/internal/apiquery"
	"github.com/openai/openai-cli/internal/requestflag"
	"github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
	"github.com/tidwall/gjson"
	"github.com/urfave/cli/v3"
)

var chatCompletionsCreate = requestflag.WithInnerFlags(cli.Command{
	Name:    "create",
	Usage:   "**Starting a new project?** We recommend trying\n[Responses](https://platform.openai.com/docs/api-reference/responses) to take\nadvantage of the latest OpenAI platform features. Compare\n[Chat Completions with Responses](https://platform.openai.com/docs/guides/responses-vs-chat-completions?api-mode=responses).",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[[]map[string]any]{
			Name:     "message",
			Usage:    "A list of messages comprising the conversation so far. Depending on the\n[model](https://platform.openai.com/docs/models) you use, different message types (modalities) are\nsupported, like [text](https://platform.openai.com/docs/guides/text-generation),\n[images](https://platform.openai.com/docs/guides/vision), and [audio](https://platform.openai.com/docs/guides/audio).\n",
			Required: true,
			BodyPath: "messages",
		},
		&requestflag.Flag[string]{
			Name:     "model",
			Usage:    "Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI\noffers a wide range of models with different capabilities, performance\ncharacteristics, and price points. Refer to the [model guide](https://platform.openai.com/docs/models)\nto browse and compare available models.\n",
			Required: true,
			BodyPath: "model",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "audio",
			Usage:    "Parameters for audio output. Required when audio output is requested with\n`modalities: [\"audio\"]`. [Learn more](https://platform.openai.com/docs/guides/audio).\n",
			BodyPath: "audio",
		},
		&requestflag.Flag[*float64]{
			Name:     "frequency-penalty",
			Usage:    "Number between -2.0 and 2.0. Positive values penalize new tokens based on\ntheir existing frequency in the text so far, decreasing the model's\nlikelihood to repeat the same line verbatim.\n",
			Default:  requestflag.Ptr[float64](0),
			BodyPath: "frequency_penalty",
		},
		&requestflag.Flag[any]{
			Name:     "function-call",
			Usage:    "Deprecated in favor of `tool_choice`.\n\nControls which (if any) function is called by the model.\n\n`none` means the model will not call a function and instead generates a\nmessage.\n\n`auto` means the model can pick between generating a message or calling a\nfunction.\n\nSpecifying a particular function via `{\"name\": \"my_function\"}` forces the\nmodel to call that function.\n\n`none` is the default when no functions are present. `auto` is the default\nif functions are present.\n",
			BodyPath: "function_call",
		},
		&requestflag.Flag[[]map[string]any]{
			Name:     "function",
			Usage:    "Deprecated in favor of `tools`.\n\nA list of functions the model may generate JSON inputs for.\n",
			BodyPath: "functions",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "logit-bias",
			Usage:    "Modify the likelihood of specified tokens appearing in the completion.\n\nAccepts a JSON object that maps tokens (specified by their token ID in the\ntokenizer) to an associated bias value from -100 to 100. Mathematically,\nthe bias is added to the logits generated by the model prior to sampling.\nThe exact effect will vary per model, but values between -1 and 1 should\ndecrease or increase likelihood of selection; values like -100 or 100\nshould result in a ban or exclusive selection of the relevant token.\n",
			BodyPath: "logit_bias",
		},
		&requestflag.Flag[*bool]{
			Name:     "logprobs",
			Usage:    "Whether to return log probabilities of the output tokens or not. If true,\nreturns the log probabilities of each output token returned in the\n`content` of `message`.\n",
			Default:  requestflag.Ptr[bool](false),
			BodyPath: "logprobs",
		},
		&requestflag.Flag[*int64]{
			Name:     "max-completion-tokens",
			Usage:    "An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and [reasoning tokens](https://platform.openai.com/docs/guides/reasoning).\n",
			BodyPath: "max_completion_tokens",
		},
		&requestflag.Flag[*int64]{
			Name:     "max-tokens",
			Usage:    "The maximum number of [tokens](/tokenizer) that can be generated in the\nchat completion. This value can be used to control\n[costs](https://openai.com/api/pricing/) for text generated via API.\n\nThis value is now deprecated in favor of `max_completion_tokens`, and is\nnot compatible with [o-series models](https://platform.openai.com/docs/guides/reasoning).\n",
			BodyPath: "max_tokens",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "metadata",
			Usage:    "Set of 16 key-value pairs that can be attached to an object. This can be\nuseful for storing additional information about the object in a structured\nformat, and querying for objects via API or the dashboard.\n\nKeys are strings with a maximum length of 64 characters. Values are strings\nwith a maximum length of 512 characters.\n",
			BodyPath: "metadata",
		},
		&requestflag.Flag[any]{
			Name:     "modality",
			Usage:    "Output types that you would like the model to generate.\nMost models are capable of generating text, which is the default:\n\n`[\"text\"]`\n\nThe `gpt-4o-audio-preview` model can also be used to\n[generate audio](https://platform.openai.com/docs/guides/audio). To request that this model generate\nboth text and audio responses, you can use:\n\n`[\"text\", \"audio\"]`\n",
			BodyPath: "modalities",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "moderation",
			Usage:    "Configuration for running moderation on the request input and generated output.\n",
			BodyPath: "moderation",
		},
		&requestflag.Flag[*int64]{
			Name:     "n",
			Usage:    "How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep `n` as `1` to minimize costs.",
			Default:  requestflag.Ptr[int64](1),
			BodyPath: "n",
		},
		&requestflag.Flag[bool]{
			Name:     "parallel-tool-calls",
			Usage:    "Whether to enable [parallel function calling](https://platform.openai.com/docs/guides/function-calling#configuring-parallel-function-calling) during tool use.",
			Default:  true,
			BodyPath: "parallel_tool_calls",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "prediction",
			Usage:    "Static predicted output content, such as the content of a text file that is\nbeing regenerated.\n",
			BodyPath: "prediction",
		},
		&requestflag.Flag[*float64]{
			Name:     "presence-penalty",
			Usage:    "Number between -2.0 and 2.0. Positive values penalize new tokens based on\nwhether they appear in the text so far, increasing the model's likelihood\nto talk about new topics.\n",
			Default:  requestflag.Ptr[float64](0),
			BodyPath: "presence_penalty",
		},
		&requestflag.Flag[*string]{
			Name:     "prompt-cache-key",
			Usage:    "Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the `user` field. [Learn more](https://platform.openai.com/docs/guides/prompt-caching).\n",
			BodyPath: "prompt_cache_key",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "prompt-cache-options",
			Usage:    "Options for prompt caching. Supported for `gpt-5.6` and later models. By default, OpenAI automatically chooses one implicit cache breakpoint. You can add explicit breakpoints to content blocks with `prompt_cache_breakpoint`. Each request can write up to four breakpoints. For cache matching, OpenAI considers up to the latest 80 breakpoints in the conversation, without a content-block lookback limit. Set `mode` to `explicit` to disable the implicit breakpoint. The `ttl` defaults to `30m`, which is currently the only supported value. See the [prompt caching guide](https://platform.openai.com/docs/guides/prompt-caching) for current details.",
			BodyPath: "prompt_cache_options",
		},
		&requestflag.Flag[*string]{
			Name:     "prompt-cache-retention",
			Usage:    "Deprecated. Use `prompt_cache_options.ttl` instead.\n\nThe retention policy for the prompt cache. Set to `24h` to enable extended prompt caching, which keeps cached prefixes active for longer, up to a maximum of 24 hours. [Learn more](https://platform.openai.com/docs/guides/prompt-caching#prompt-cache-retention).\nThis field expresses a maximum retention policy, while\n`prompt_cache_options.ttl` expresses a minimum cache lifetime. The two\nfields are independent and do not interact.\nFor `gpt-5.5`, `gpt-5.5-pro`, and future models, only `24h` is supported.\n\nFor older models that support both `in_memory` and `24h`, the default depends on your organization's data retention policy:\n  - Organizations without ZDR enabled default to `24h`.\n  - Organizations with ZDR enabled default to `in_memory` when `prompt_cache_retention` is not specified.\n",
			BodyPath: "prompt_cache_retention",
		},
		&requestflag.Flag[*string]{
			Name:     "reasoning-effort",
			Usage:    "Constrains effort on reasoning for reasoning models. Currently supported\nvalues are `none`, `minimal`, `low`, `medium`, `high`, `xhigh`, and `max`.\nReducing reasoning effort can result in faster responses and fewer tokens\nused on reasoning in a response. Not all reasoning models support every\nvalue. See the\n[reasoning guide](https://platform.openai.com/docs/guides/reasoning)\nfor model-specific support.\n",
			Default:  requestflag.Ptr[string]("medium"),
			BodyPath: "reasoning_effort",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "response-format",
			Usage:    "An object specifying the format that the model must output.\n\nSetting to `{ \"type\": \"json_schema\", \"json_schema\": {...} }` enables\nStructured Outputs which ensures the model will match your supplied JSON\nschema. Learn more in the [Structured Outputs\nguide](https://platform.openai.com/docs/guides/structured-outputs).\n\nSetting to `{ \"type\": \"json_object\" }` enables the older JSON mode, which\nensures the message the model generates is valid JSON. Using `json_schema`\nis preferred for models that support it.\n",
			BodyPath: "response_format",
		},
		&requestflag.Flag[*string]{
			Name:     "safety-identifier",
			Usage:    "A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies.\nThe IDs should be a string that uniquely identifies each user, with a maximum length of 64 characters. We recommend hashing their username or email address, in order to avoid sending us any identifying information. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).\n",
			BodyPath: "safety_identifier",
		},
		&requestflag.Flag[*int64]{
			Name:     "seed",
			Usage:    "This feature is in Beta.\nIf specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.\nDeterminism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend.\n",
			BodyPath: "seed",
		},
		&requestflag.Flag[*string]{
			Name:     "service-tier",
			Usage:    "Specifies the processing type used for serving the request.\n  - If set to 'auto', then the request will be processed with the service tier configured in the Project settings. Unless otherwise configured, the Project will use 'default'.\n  - If set to 'default', then the request will be processed with the standard pricing and performance for the selected model.\n  - If set to '[flex](https://platform.openai.com/docs/guides/flex-processing)' or '[priority](https://openai.com/api-priority-processing/)', then the request will be processed with the corresponding service tier.\n  - When not set, the default behavior is 'auto'.\n\n  When the `service_tier` parameter is set, the response body will include the `service_tier` value based on the processing mode actually used to serve the request. This response value may be different from the value set in the parameter.\n",
			Default:  requestflag.Ptr[string]("auto"),
			BodyPath: "service_tier",
		},
		&requestflag.Flag[any]{
			Name:     "stop",
			Usage:    "Not supported with latest reasoning models `o3` and `o4-mini`.\n\nUp to 4 sequences where the API will stop generating further tokens. The\nreturned text will not contain the stop sequence.\n",
			BodyPath: "stop",
		},
		&requestflag.Flag[*bool]{
			Name:     "store",
			Usage:    "Whether or not to store the output of this chat completion request for\nuse in our [model distillation](https://platform.openai.com/docs/guides/distillation) or\n[evals](https://platform.openai.com/docs/guides/evals) products.\n\nSupports text and image inputs. Note: image inputs over 8MB will be dropped.\n",
			Default:  requestflag.Ptr[bool](false),
			BodyPath: "store",
		},
		&requestflag.Flag[*bool]{
			Name:     "stream",
			Usage:    "If set to true, the model response data will be streamed to the client\nas it is generated using [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format).\nSee the [Streaming section below](https://platform.openai.com/docs/api-reference/chat/streaming)\nfor more information, along with the [streaming responses](https://platform.openai.com/docs/guides/streaming-responses)\nguide for more information on how to handle the streaming events.\n",
			Default:  requestflag.Ptr[bool](false),
			BodyPath: "stream",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "stream-options",
			Usage:    "Options for streaming response. Only set this when you set `stream: true`.\n",
			BodyPath: "stream_options",
		},
		&requestflag.Flag[*float64]{
			Name:     "temperature",
			Usage:    "What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.\nWe generally recommend altering this or `top_p` but not both.\n",
			Default:  requestflag.Ptr[float64](1),
			BodyPath: "temperature",
		},
		&requestflag.Flag[any]{
			Name:     "tool-choice",
			Usage:    "Controls which (if any) tool is called by the model.\n`none` means the model will not call any tool and instead generates a message.\n`auto` means the model can pick between generating a message or calling one or more tools.\n`required` means the model must call one or more tools.\nSpecifying a particular tool via `{\"type\": \"function\", \"function\": {\"name\": \"my_function\"}}` forces the model to call that tool.\n\n`none` is the default when no tools are present. `auto` is the default if tools are present.\n",
			BodyPath: "tool_choice",
		},
		&requestflag.Flag[[]map[string]any]{
			Name:     "tool",
			Usage:    "A list of tools the model may call. You can provide either\n[custom tools](https://platform.openai.com/docs/guides/function-calling#custom-tools) or\n[function tools](https://platform.openai.com/docs/guides/function-calling).\n",
			BodyPath: "tools",
		},
		&requestflag.Flag[*int64]{
			Name:     "top-logprobs",
			Usage:    "An integer between 0 and 20 specifying the maximum number of most likely\ntokens to return at each token position, each with an associated log\nprobability. In some cases, the number of returned tokens may be fewer than\nrequested.\n`logprobs` must be set to `true` if this parameter is used.\n",
			BodyPath: "top_logprobs",
		},
		&requestflag.Flag[*float64]{
			Name:     "top-p",
			Usage:    "An alternative to sampling with temperature, called nucleus sampling,\nwhere the model considers the results of the tokens with top_p probability\nmass. So 0.1 means only the tokens comprising the top 10% probability mass\nare considered.\n\nWe generally recommend altering this or `temperature` but not both.\n",
			Default:  requestflag.Ptr[float64](1),
			BodyPath: "top_p",
		},
		&requestflag.Flag[string]{
			Name:     "user",
			Usage:    "This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key` instead to maintain caching optimizations.\nA stable identifier for your end-users.\nUsed to boost cache hit rates by better bucketing similar requests and  to help OpenAI detect and prevent abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).\n",
			BodyPath: "user",
		},
		&requestflag.Flag[*string]{
			Name:     "verbosity",
			Usage:    "Constrains the verbosity of the model's response. Lower values will result in\nmore concise responses, while higher values will result in more verbose responses.\nCurrently supported values are `low`, `medium`, and `high`. The default is\n`medium`.\n",
			Default:  requestflag.Ptr[string]("medium"),
			BodyPath: "verbosity",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "web-search-options",
			Usage:    "This tool searches the web for relevant results to use in a response.\nLearn more about the [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).\n",
			BodyPath: "web_search_options",
		},
		&requestflag.Flag[int64]{
			Name:  "max-items",
			Usage: "The maximum number of items to return (use -1 for unlimited).",
		},
	},
	Action:          handleChatCompletionsCreate,
	HideHelpCommand: true,
}, map[string][]requestflag.HasOuterFlag{
	"audio": {
		&requestflag.InnerFlag[string]{
			Name:       "audio.format",
			Usage:      "Specifies the output audio format. Must be one of `wav`, `mp3`, `flac`,\n`opus`, or `pcm16`.\n",
			InnerField: "format",
		},
		&requestflag.InnerFlag[any]{
			Name:       "audio.voice",
			Usage:      "The voice the model uses to respond. Supported built-in voices are\n`alloy`, `ash`, `ballad`, `coral`, `echo`, `fable`, `nova`, `onyx`,\n`sage`, `shimmer`, `marin`, and `cedar`. You may also provide a\ncustom voice object with an `id`, for example `{ \"id\": \"voice_1234\" }`.\n",
			InnerField: "voice",
		},
	},
	"function": {
		&requestflag.InnerFlag[string]{
			Name:       "function.name",
			Usage:      "The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.",
			InnerField: "name",
		},
		&requestflag.InnerFlag[string]{
			Name:       "function.description",
			Usage:      "A description of what the function does, used by the model to choose when and how to call the function.",
			InnerField: "description",
		},
		&requestflag.InnerFlag[map[string]any]{
			Name:       "function.parameters",
			Usage:      "The parameters the functions accepts, described as a JSON Schema object. See the [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format. \n\nOmitting `parameters` defines a function with an empty parameter list.",
			InnerField: "parameters",
		},
	},
	"moderation": {
		&requestflag.InnerFlag[string]{
			Name:       "moderation.model",
			Usage:      "The moderation model to use for moderated completions, e.g. 'omni-moderation-latest'.",
			InnerField: "model",
		},
		&requestflag.InnerFlag[map[string]any]{
			Name:       "moderation.policy",
			Usage:      "The policy to apply to moderated response input and output.",
			InnerField: "policy",
		},
	},
	"prediction": {
		&requestflag.InnerFlag[any]{
			Name:       "prediction.content",
			Usage:      "The content that should be matched when generating a model response.\nIf generated tokens would match this content, the entire model response\ncan be returned much more quickly.\n",
			InnerField: "content",
		},
		&requestflag.InnerFlag[string]{
			Name:       "prediction.type",
			Usage:      "The type of the predicted content you want to provide. This type is\ncurrently always `content`.\n",
			InnerField: "type",
		},
	},
	"prompt-cache-options": {
		&requestflag.InnerFlag[string]{
			Name:       "prompt-cache-options.mode",
			Usage:      "Controls whether OpenAI automatically creates an implicit cache breakpoint. Defaults to `implicit`. With `implicit`, OpenAI creates one implicit breakpoint and writes up to the latest three explicit breakpoints in the request. With `explicit`, OpenAI does not create an implicit breakpoint and writes up to the latest four explicit breakpoints. If there are no explicit breakpoints, the request does not use prompt caching.",
			InnerField: "mode",
		},
		&requestflag.InnerFlag[string]{
			Name:       "prompt-cache-options.ttl",
			Usage:      "The minimum lifetime applied to every implicit and explicit cache breakpoint written by the request. Defaults to `30m`, which is currently the only supported value. The backend may retain cache entries for longer.",
			InnerField: "ttl",
		},
	},
	"stream-options": {
		&requestflag.InnerFlag[bool]{
			Name:       "stream-options.include-obfuscation",
			Usage:      "When true, stream obfuscation will be enabled. Stream obfuscation adds\nrandom characters to an `obfuscation` field on streaming delta events to\nnormalize payload sizes as a mitigation to certain side-channel attacks.\nThese obfuscation fields are included by default, but add a small amount\nof overhead to the data stream. You can set `include_obfuscation` to\nfalse to optimize for bandwidth if you trust the network links between\nyour application and the OpenAI API.\n",
			InnerField: "include_obfuscation",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "stream-options.include-usage",
			Usage:      "If set, an additional chunk will be streamed before the `data: [DONE]`\nmessage. The `usage` field on this chunk shows the token usage statistics\nfor the entire request, and the `choices` field will always be an empty\narray.\n\nAll other chunks will also include a `usage` field, but with a null\nvalue. **NOTE:** If the stream is interrupted, you may not receive the\nfinal usage chunk which contains the total token usage for the request.\n",
			InnerField: "include_usage",
		},
	},
	"web-search-options": {
		&requestflag.InnerFlag[string]{
			Name:       "web-search-options.search-context-size",
			Usage:      "High level guidance for the amount of context window space to use for the \nsearch. One of `low`, `medium`, or `high`. `medium` is the default.\n",
			InnerField: "search_context_size",
		},
		&requestflag.InnerFlag[map[string]any]{
			Name:       "web-search-options.user-location",
			Usage:      "Approximate location parameters for the search.\n",
			InnerField: "user_location",
		},
	},
})

var chatCompletionsRetrieve = cli.Command{
	Name:    "retrieve",
	Usage:   "Get a stored chat completion. Only Chat Completions that have been created with\nthe `store` parameter set to `true` will be returned.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "completion-id",
			Required:  true,
			PathParam: "completion_id",
		},
	},
	Action:          handleChatCompletionsRetrieve,
	HideHelpCommand: true,
}

var chatCompletionsUpdate = cli.Command{
	Name:    "update",
	Usage:   "Modify a stored chat completion. Only Chat Completions that have been created\nwith the `store` parameter set to `true` can be modified. Currently, the only\nsupported modification is to update the `metadata` field.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "completion-id",
			Required:  true,
			PathParam: "completion_id",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "metadata",
			Usage:    "Set of 16 key-value pairs that can be attached to an object. This can be\nuseful for storing additional information about the object in a structured\nformat, and querying for objects via API or the dashboard.\n\nKeys are strings with a maximum length of 64 characters. Values are strings\nwith a maximum length of 512 characters.\n",
			Required: true,
			BodyPath: "metadata",
		},
	},
	Action:          handleChatCompletionsUpdate,
	HideHelpCommand: true,
}

var chatCompletionsList = cli.Command{
	Name:    "list",
	Usage:   "List stored Chat Completions. Only Chat Completions that have been stored with\nthe `store` parameter set to `true` will be returned.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "after",
			Usage:     "Identifier for the last chat completion from the previous pagination request.",
			QueryPath: "after",
		},
		&requestflag.Flag[int64]{
			Name:      "limit",
			Usage:     "Number of Chat Completions to retrieve.",
			Default:   20,
			QueryPath: "limit",
		},
		&requestflag.Flag[map[string]any]{
			Name:      "metadata",
			Usage:     "Set of 16 key-value pairs that can be attached to an object. This can be\nuseful for storing additional information about the object in a structured\nformat, and querying for objects via API or the dashboard.\n\nKeys are strings with a maximum length of 64 characters. Values are strings\nwith a maximum length of 512 characters.\n",
			QueryPath: "metadata",
		},
		&requestflag.Flag[string]{
			Name:      "model",
			Usage:     "The model used to generate the Chat Completions.",
			QueryPath: "model",
		},
		&requestflag.Flag[string]{
			Name:      "order",
			Usage:     "Sort order for Chat Completions by timestamp. Use `asc` for ascending order or `desc` for descending order. Defaults to `asc`.",
			Default:   "asc",
			QueryPath: "order",
		},
		&requestflag.Flag[int64]{
			Name:  "max-items",
			Usage: "The maximum number of items to return (use -1 for unlimited).",
		},
	},
	Action:          handleChatCompletionsList,
	HideHelpCommand: true,
}

var chatCompletionsDelete = cli.Command{
	Name:    "delete",
	Usage:   "Delete a stored chat completion. Only Chat Completions that have been created\nwith the `store` parameter set to `true` can be deleted.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "completion-id",
			Required:  true,
			PathParam: "completion_id",
		},
	},
	Action:          handleChatCompletionsDelete,
	HideHelpCommand: true,
}

func handleChatCompletionsCreate(ctx context.Context, cmd *cli.Command) error {
	client := openai.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatBrackets,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	params := openai.ChatCompletionNewParams{}

	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	if requestflag.FlagBool(cmd, "stream") {
		stream := client.Chat.Completions.NewStreaming(ctx, params, options...)
		maxItems := int64(-1)
		if cmd.IsSet("max-items") {
			maxItems = cmd.Value("max-items").(int64)
		}
		return ShowJSONIterator(stream, maxItems, ShowJSONOpts{
			ExplicitFormat: explicitFormat,
			Format:         format,
			RawOutput:      cmd.Root().Bool("raw-output"),
			Title:          "chat:completions create",
			Transform:      transform,
		})
	} else {
		var res []byte
		options = append(options, option.WithResponseBodyInto(&res))
		_, err = client.Chat.Completions.New(ctx, params, options...)
		if err != nil {
			return err
		}

		obj := gjson.ParseBytes(res)
		return ShowJSON(obj, ShowJSONOpts{
			ExplicitFormat: explicitFormat,
			Format:         format,
			RawOutput:      cmd.Root().Bool("raw-output"),
			Title:          "chat:completions create",
			Transform:      transform,
		})
	}
}

func handleChatCompletionsRetrieve(ctx context.Context, cmd *cli.Command) error {
	client := openai.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("completion-id") && len(unusedArgs) > 0 {
		cmd.Set("completion-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatBrackets,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Chat.Completions.Get(ctx, cmd.Value("completion-id").(string), options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "chat:completions retrieve",
		Transform:      transform,
	})
}

func handleChatCompletionsUpdate(ctx context.Context, cmd *cli.Command) error {
	client := openai.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("completion-id") && len(unusedArgs) > 0 {
		cmd.Set("completion-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatBrackets,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	params := openai.ChatCompletionUpdateParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Chat.Completions.Update(
		ctx,
		cmd.Value("completion-id").(string),
		params,
		options...,
	)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "chat:completions update",
		Transform:      transform,
	})
}

func handleChatCompletionsList(ctx context.Context, cmd *cli.Command) error {
	client := openai.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatBrackets,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	params := openai.ChatCompletionListParams{}

	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	if format == "raw" {
		var res []byte
		options = append(options, option.WithResponseBodyInto(&res))
		_, err = client.Chat.Completions.List(ctx, params, options...)
		if err != nil {
			return err
		}
		obj := gjson.ParseBytes(res)
		return ShowJSON(obj, ShowJSONOpts{
			ExplicitFormat: explicitFormat,
			Format:         format,
			RawOutput:      cmd.Root().Bool("raw-output"),
			Title:          "chat:completions list",
			Transform:      transform,
		})
	} else {
		iter := client.Chat.Completions.ListAutoPaging(ctx, params, options...)
		maxItems := int64(-1)
		if cmd.IsSet("max-items") {
			maxItems = cmd.Value("max-items").(int64)
		}
		return ShowJSONIterator(iter, maxItems, ShowJSONOpts{
			ExplicitFormat: explicitFormat,
			Format:         format,
			RawOutput:      cmd.Root().Bool("raw-output"),
			Title:          "chat:completions list",
			Transform:      transform,
		})
	}
}

func handleChatCompletionsDelete(ctx context.Context, cmd *cli.Command) error {
	client := openai.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("completion-id") && len(unusedArgs) > 0 {
		cmd.Set("completion-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatBrackets,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Chat.Completions.Delete(ctx, cmd.Value("completion-id").(string), options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "chat:completions delete",
		Transform:      transform,
	})
}
