name: Setup Go
description: 'Sets up the Go environment'
runs:
  using: composite
  steps:
    - name: Setup go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version-file: ./go.mod

    - name: Bootstrap
      shell: bash
      run: ./scripts/bootstrap
