name: Setup Go
description: 'Sets up the Go environment'
runs:
  using: composite
  steps:
    - name: Setup go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: .go-version
        check-latest: true

    - name: Bootstrap
      shell: bash
      run: ./scripts/bootstrap
