//go:build ignore

// Generate explicit classes from the pinned Unicode data. This is build tooling,
// not a runtime data download or an implementation of tokenization.
package main

import (
	"bufio"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
)

const expected = "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f"

func main() {
	dataPath := flag.String("data", "", "path to the pinned UnicodeData-16.0.0.txt")
	outputPath := flag.String("output", "internal/tokenizer/unicode16.go", "generated Go output path")
	flag.Parse()
	if *dataPath == "" || flag.NArg() != 0 {
		flag.Usage()
		os.Exit(2)
	}
	data, err := os.ReadFile(*dataPath)
	check(err)
	if fmt.Sprintf("%x", sha256.Sum256(data)) != expected {
		panic("UnicodeData16 hash mismatch")
	}
	category := make([]string, 0x110000)
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	first := -1
	firstCategory := ""
	for scanner.Scan() {
		fields := strings.Split(scanner.Text(), ";")
		if len(fields) != 15 {
			panic("invalid UnicodeData row")
		}
		value, err := strconv.ParseInt(fields[0], 16, 32)
		check(err)
		point := int(value)
		if strings.HasSuffix(fields[1], ", First>") {
			if first >= 0 {
				panic("nested UnicodeData range")
			}
			first, firstCategory = point, fields[2]
			continue
		}
		if strings.HasSuffix(fields[1], ", Last>") {
			if first < 0 || firstCategory != fields[2] || point < first {
				panic("invalid UnicodeData range")
			}
			for i := first; i <= point; i++ {
				category[i] = fields[2]
			}
			first = -1
			continue
		}
		if first >= 0 {
			panic("unterminated UnicodeData range")
		}
		category[point] = fields[2]
	}
	check(scanner.Err())
	if first >= 0 {
		panic("unterminated UnicodeData range")
	}
	predicates := map[string]func(int, string) bool{
		"Letters": func(_ int, c string) bool { return strings.HasPrefix(c, "L") },
		"Numbers": func(_ int, c string) bool { return strings.HasPrefix(c, "N") },
		"Upper": func(_ int, c string) bool {
			return c == "Lu" || c == "Lt" || c == "Lm" || c == "Lo" || strings.HasPrefix(c, "M")
		},
		"Lower": func(_ int, c string) bool { return c == "Ll" || c == "Lm" || c == "Lo" || strings.HasPrefix(c, "M") },
		// Unicode16 White_Space comprises Zs/Zl/Zp, TAB through CR, and NEL.
		// These are the complete White_Space ranges in Unicode 16.0.0.
		"Whitespace": func(r int, c string) bool {
			return c == "Zs" || c == "Zl" || c == "Zp" || r >= 9 && r <= 13 || r == 0x85
		},
	}
	var names []string
	for name := range predicates {
		names = append(names, name)
	}
	sort.Strings(names)
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by scripts/generate-tokenizer-unicode.go; DO NOT EDIT.\n// UnicodeData 16.0.0 SHA-256: %s.\n// Unicode-3.0 license: see LICENSES.txt.\npackage tokenizer\n\n", expected)
	for _, name := range names {
		predicate := predicates[name]
		var content strings.Builder
		ranges, scalars := 0, 0
		for point := 0; point < len(category); point++ {
			if !predicate(point, category[point]) {
				continue
			}
			start := point
			for point+1 < len(category) && predicate(point+1, category[point+1]) {
				point++
			}
			content.WriteString(regexRune(rune(start)))
			if point != start {
				content.WriteByte('-')
				content.WriteString(regexRune(rune(point)))
			}
			ranges++
			scalars += point - start + 1
		}
		fmt.Fprintf(&out, "// %s: %d ranges, %d code points.\nconst unicode16%s = %s\n\n", name, ranges, scalars, name, strconv.QuoteToASCII(content.String()))
	}
	formatted, err := format.Source([]byte(out.String()))
	check(err)
	check(os.WriteFile(*outputPath, formatted, 0644))
}

func regexRune(value rune) string {
	if value < 128 {
		return fmt.Sprintf(`\x%02X`, value)
	}
	return string(value)
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
