name: CI
permissions: {}
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types:
      - checks_requested

jobs:
  lint:
    timeout-minutes: 10
    name: lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-go

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run lints
        run: ./scripts/lint

  build-artifacts:
    timeout-minutes: 10
    name: build artifacts
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-go

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Read GoReleaser version
        id: goreleaser-version
        run: echo "version=$(cat .goreleaser-version)" >> "$GITHUB_OUTPUT"

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          version: ${{ steps.goreleaser-version.outputs.version }}
          args: release --snapshot --clean --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    timeout-minutes: 10
    name: build
    needs:
      - build-artifacts
    if: always()
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Require successful build
        env:
          BUILD_RESULT: ${{ needs.build-artifacts.result }}
        run: |
          if [[ "$BUILD_RESULT" != "success" ]]; then
            echo "Build artifacts failed: $BUILD_RESULT"
            exit 1
          fi

  test:
    timeout-minutes: 10
    name: test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-go

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run tests
        run: ./scripts/test
