name: Create releases
on:
  schedule:
    - cron: '0 5 * * *' # every day at 5am UTC
  push:
    branches:
      - main

jobs:
  release:
    name: release
    if: github.ref == 'refs/heads/main' && github.repository == 'openai/openai-cli'
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ github.token }}
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    name: publish
    needs: release
    if: needs.release.outputs.release_created == 'true'
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-release.yml
    with:
      tag: ${{ needs.release.outputs.tag_name }}
